### ISSUE TITLE
Error "Maximum call stack size exceeded" after upgrading to 2.6.15+

### ISSUE THREAD

**Issue by im1x** [xuliangzhan/vxe-table#506]
### Describe the bug
I have a problem after updating to version 2.6.15+. Before 2.6.15 everything works well.

### Reproduction link
Unfortunately, I am not yet ready to provide an example showing a reproduction of errors.

### Error message or screenshots
I get several kinds of errors
```
vue.common.dev.js:1893 RangeError: Maximum call stack size exceeded
    at Function.getDefault [as a] (bootstrap:880)
    at Object.i18n (main.js:27)
    at Object.t (index.js:102)
    at Object.i18n (main.js:27)
    at Object.t (index.js:102)
    at Object.i18n (main.js:27)
    at Object.t (index.js:102)
    at Object.i18n (main.js:27)
    at Object.t (index.js:102)
    at Object.i18n (main.js:27)
```
In line 27, I have the translation settings for the table:
```
25: Vue.use(VXETable);
26: VXETable.setup({
27:  i18n: (key, value) => VXETable.t(EnLocat, key)
28: });
```
index.js is the file vxe-table/lib/v-x-e-table/index.js and points to these lines:
```
100: var VXETable = {
101:  t: function t(key) {
102:    return _conf.default.i18n(key);
103:  },
```
Another error:
```
methods.js:3361 Uncaught (in promise) TypeError: tableBody.$el.querySelector is not a function
    at VueComponent.updateScrollXSpace (methods.js:3361)
    at methods.js:3294
```
In the file vxe-table/lib/table/src/methods.js on 3361 line, this code:
`var bodyElem = tableBody.$el.querySelector('.vxe-table--body');`

### Expected behavior
 ?

### Version

- os: Win10
- browser: Chrome 78.0.3904.87
- vue: 2.6.10
- vxe-table: 2.6.17

**Comment by xlz26296** [comment]
这个后续版本不能这么用，VXETable.t 会默认指向 i18n，会造成自己调自己死循环。
参考 https://github.com/xuliangzhan/vxe-table-demo

**Comment by im1x** [comment]
> 2.6.15+不能这么使用，VXETable.t 会默认指向 i18n，会造成自己调自己死循环。
> 参考 https://github.com/xuliangzhan/vxe-table-demo

Thanks, that helped!
I try to keep track of vxe-table changes, but I have not seen information about this change.
